### ISSUE TITLE
I can't run the program

### ISSUE THREAD

**Issue by JLUssh** [rruisong/FedD3#1]
Thank you for your willingness to open source your code and your inspiring work.
  I also have published a paper in IJCNN in 2024 about this topic, and want to extend it to a journal. I want reference and use your work as a contrast experiment. 
  But I have trouble to run your code. Could you give me some advice on how to run your program if you would like? I followed the readme txt and installed related libs, but when I run, there has some mistake I couldn't resolve.
  ![image](https://github.com/rruisong/FedD3/assets/99879907/44d48798-f1cb-469a-8aeb-d9d275dbbd8d)
  I sincerely hope to get your help.

**Comment by rruisong** [comment]
Thank you for your interest in our work. Congratulations on your new publication!

From your screenshot, it appears there is an issue with the JAX package. Could you please check if JAX version 0.3.7 has been installed successfully?

**Comment by JLUssh** [comment]
> Thank you for your interest in our work. Congratulations on your new publication!
> 
> From your screenshot, it appears there is an issue with the JAX package. Could you please check if JAX version 0.3.7 has been installed successfully?

Thank for your replay, and I'm sorry to have taken up your time.
```
 Package                      Version
---------------------------- -----------
absl-py                      2.1.0
astunparse                   1.6.3
cachetools                   5.3.3
certifi                      2024.6.2
charset-normalizer           3.3.2
colorama                     0.4.6
cycler                       0.12.1
dm-tree                      0.1.8
flatbuffers                  24.3.25
frozendict                   2.4.4
gast                         0.4.0
google-auth                  2.30.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.64.1
h5py                         3.11.0
idna                         3.7
importlib_metadata           7.1.0
jax                          0.3.7
jaxlib                       0.3.7
joblib                       1.4.2
keopscore                    2.2.3
keras                        2.13.1
kiwisolver                   1.4.5
libclang                     18.1.1
Markdown                     3.6
MarkupSafe                   2.1.5
matplotlib                   3.4.3
ml-dtypes                    0.2.0
neural-tangents              0.6.0
numpy                        1.24.3
oauthlib                     3.2.2
opencv-python                4.5.3.56
opt-einsum                   3.3.0
packaging                    24.0
Pillow                       8.2.0
pip                          22.3.1
protobuf                     4.25.3
pyasn1                       0.6.0
pyasn1_modules               0.4.0
pybind11                     2.12.0
pykeops                      2.2.3
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
requests                     2.32.3
requests-oauthlib            2.0.0
rsa                          4.9
scikit-learn                 0.24.2
scipy                        1.10.1
setuptools                   65.5.1
six                          1.16.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.2
tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-intel             2.13.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
tf2jax                       0.3.6
threadpoolctl                3.5.0
torch                        1.8.1
torchvision                  0.9.1
tqdm                         4.61.2
typing_extensions            4.5.0
urllib3                      2.2.1
Werkzeug                     3.0.3
wheel                        0.38.4
wrapt                        1.16.0
zipp                         3.19.2
```
the above are my installed libs, which I think is follow the suggestion of readme and the jax version0.3.7 has been installed. when I start the program like the command 

```
python fedd3_main.py -nc 500 -ck 10 -ds 'MNIST' -md 'LeNet' -is 0 -rr 'results' -sne 500 -sbs 50 -slr 0.001 -smt 0.9 -snw 1 -cis 'kip_distill' -cnd 10 -cil 0.004 -cib 10 -cie 3000 -cit 0.999
```

the error has jumped out.
![image](https://github.com/rruisong/FedD3/assets/99879907/8906e937-8405-4f69-9a4d-3766d7109e2e)
![image](https://github.com/rruisong/FedD3/assets/99879907/7a9aef4e-f763-49af-b733-29ce3d91bc47)

I think the error is from the inner, so I don't know what to do.

Could you give me some advices? Thanks a lot!

**Comment by rruisong** [comment]
Your list of the package looks good. But still, could you please try installing both jax and jaxlib with version 0.3.15 and then run the code again?

**Comment by JLUssh** [comment]
> Your list of the package looks good. But still, could you please try installing both jax and jaxlib with version 0.3.15 and then run the code again?

Thank for your replay!
I found the version of Python shouldn't be 3.8 as requested in the readme file, and then install the related latest packages without follow the version of requirement file, it works....
I don't konw why...but it fixed.
Thanks for your help!

**Comment by rruisong** [comment]
Thanks for resolving the issue with helpful information!
